on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Change directory to neo_explorer
        run: cd neo_explorer

      - name: Run Zig Build
        run: zig build -Doptimize=ReleaseFast
        working-directory: neo_explorer

      - name: Start the Server
        run: ./zig-out/bin/neo-explorer --port=6969 --addr=0.0.0.0 &
        working-directory: neo_explorer
